# Generated by Django 6.0.2 on 2026-02-15 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_attendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-attendance_date', 'student_id']},
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='student',
            new_name='student_id',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student_id', 'attendance_date')},
        ),
    ]
