# Generated by Django 6.0.2 on 2026-04-13 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_tutorial_studenttutorialprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-attendance_date', 'student']},
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='student_id',
            new_name='student',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'attendance_date')},
        ),
    ]
