# Generated by Django 6.0.2 on 2026-04-23 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_attendance_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.IntegerField(unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['period_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['day_number']},
        ),
        migrations.RemoveField(
            model_name='day',
            name='calendar_date',
        ),
        migrations.AddField(
            model_name='day',
            name='day_number',
            field=models.IntegerField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], null=True, unique=True),
        ),
        migrations.AddField(
            model_name='day',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='day',
            name='name',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('room', models.CharField(blank=True, max_length=50)),
                ('is_break', models.BooleanField(default=False)),
                ('break_name', models.CharField(blank=True, max_length=100)),
                ('academic_year', models.CharField(default='2024', max_length=20)),
                ('term', models.CharField(default='Term 1', max_length=20)),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='management.class')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.day')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.period')),
                ('teacher', models.ForeignKey(limit_choices_to={'groups__name': 'Teachers'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['class_assigned__name', 'day__day_number', 'period__period_number'],
                'unique_together': {('class_assigned', 'day', 'period', 'academic_year', 'term')},
            },
        ),
    ]
